/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_type = 1,
  anon_sym_EQ = 2,
  sym_attribute_name = 3,
  sym_xpath = 4,
  sym_string = 5,
  sym_number = 6,
  anon_sym_true = 7,
  anon_sym_false = 8,
  sym_comment = 9,
  sym__newline = 10,
  sym__indent = 11,
  sym__dedent = 12,
  sym_document = 13,
  sym_statement = 14,
  sym_block = 15,
  sym_positional_value = 16,
  sym_attribute = 17,
  sym_value = 18,
  sym_boolean = 19,
  aux_sym_document_repeat1 = 20,
  aux_sym_statement_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_type] = "type",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_xpath] = "xpath",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_document] = "document",
  [sym_statement] = "statement",
  [sym_block] = "block",
  [sym_positional_value] = "positional_value",
  [sym_attribute] = "attribute",
  [sym_value] = "value",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_statement_repeat1] = "statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_type] = sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_xpath] = sym_xpath,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_document] = sym_document,
  [sym_statement] = sym_statement,
  [sym_block] = sym_block,
  [sym_positional_value] = sym_positional_value,
  [sym_attribute] = sym_attribute,
  [sym_value] = sym_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_xpath] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_positional_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute = 1,
  field_name = 2,
  field_type = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute] = "attribute",
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_attribute, 0},
  [2] =
    {field_type, 0},
    {field_value, 1},
  [4] =
    {field_attribute, 1, .inherited = true},
    {field_type, 0},
  [6] =
    {field_attribute, 0, .inherited = true},
    {field_attribute, 1, .inherited = true},
  [8] =
    {field_name, 0},
    {field_value, 2},
  [10] =
    {field_attribute, 2, .inherited = true},
    {field_type, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 6,
  [17] = 9,
  [18] = 11,
  [19] = 5,
  [20] = 20,
  [21] = 21,
  [22] = 7,
  [23] = 8,
  [24] = 12,
  [25] = 14,
  [26] = 20,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 29,
  [37] = 37,
  [38] = 31,
  [39] = 30,
  [40] = 40,
  [41] = 41,
  [42] = 32,
  [43] = 34,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\\') SKIP(12);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(5);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '\\') SKIP(2);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '>') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 11:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(16);
      END_STATE();
    case 12:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(16);
      if (lookahead == '\r') SKIP(11);
      END_STATE();
    case 13:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(15);
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '\r') SKIP(13);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '\\') SKIP(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '>') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\\') SKIP(12);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('<' <= lookahead && lookahead <= '>') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 's') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_xpath);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '\\') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_xpath);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '\\') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 15, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 15, .external_lex_state = 3},
  [6] = {.lex_state = 15, .external_lex_state = 3},
  [7] = {.lex_state = 5, .external_lex_state = 2},
  [8] = {.lex_state = 5, .external_lex_state = 2},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15, .external_lex_state = 3},
  [12] = {.lex_state = 5, .external_lex_state = 2},
  [13] = {.lex_state = 5, .external_lex_state = 2},
  [14] = {.lex_state = 15, .external_lex_state = 4},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15, .external_lex_state = 5},
  [17] = {.lex_state = 15, .external_lex_state = 4},
  [18] = {.lex_state = 15, .external_lex_state = 5},
  [19] = {.lex_state = 15, .external_lex_state = 5},
  [20] = {.lex_state = 15, .external_lex_state = 5},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 5, .external_lex_state = 2},
  [23] = {.lex_state = 5, .external_lex_state = 2},
  [24] = {.lex_state = 5, .external_lex_state = 2},
  [25] = {.lex_state = 15, .external_lex_state = 4},
  [26] = {.lex_state = 15, .external_lex_state = 3},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15, .external_lex_state = 4},
  [33] = {.lex_state = 5, .external_lex_state = 2},
  [34] = {.lex_state = 15, .external_lex_state = 4},
  [35] = {.lex_state = 5, .external_lex_state = 2},
  [36] = {.lex_state = 15, .external_lex_state = 4},
  [37] = {.lex_state = 5, .external_lex_state = 2},
  [38] = {.lex_state = 15, .external_lex_state = 4},
  [39] = {.lex_state = 15, .external_lex_state = 4},
  [40] = {.lex_state = 5, .external_lex_state = 2},
  [41] = {.lex_state = 5, .external_lex_state = 2},
  [42] = {.lex_state = 15},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [sym_xpath] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(44),
    [sym_statement] = STATE(21),
    [aux_sym_document_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_type] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_positional_value] = STATE(7),
    [sym_attribute] = STATE(33),
    [sym_boolean] = STATE(35),
    [aux_sym_statement_repeat1] = STATE(8),
    [sym_attribute_name] = ACTIONS(11),
    [sym_xpath] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_positional_value] = STATE(22),
    [sym_attribute] = STATE(33),
    [sym_boolean] = STATE(35),
    [aux_sym_statement_repeat1] = STATE(23),
    [sym_attribute_name] = ACTIONS(11),
    [sym_xpath] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(40), 1,
      sym_boolean,
    STATE(41), 1,
      sym_value,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(21), 3,
      sym_xpath,
      sym_string,
      sym_number,
  [19] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__indent,
    STATE(29), 1,
      sym_block,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      sym_type,
  [33] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__indent,
    STATE(43), 1,
      sym_block,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_type,
  [47] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(31), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [63] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(33), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [79] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_type,
    STATE(9), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [93] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_type,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(15), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__indent,
    STATE(42), 1,
      sym_block,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      sym_type,
  [121] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(44), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [137] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_attribute_name,
    ACTIONS(49), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [153] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_type,
    ACTIONS(53), 1,
      sym__dedent,
    STATE(17), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_type,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [181] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym__indent,
    STATE(34), 1,
      sym_block,
    ACTIONS(27), 2,
      sym__dedent,
      sym_type,
  [195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym__dedent,
    ACTIONS(59), 1,
      sym_type,
    STATE(17), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [209] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym__indent,
    STATE(32), 1,
      sym_block,
    ACTIONS(42), 2,
      sym__dedent,
      sym_type,
  [223] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym__indent,
    STATE(36), 1,
      sym_block,
    ACTIONS(23), 2,
      sym__dedent,
      sym_type,
  [237] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym__indent,
    STATE(38), 1,
      sym_block,
    ACTIONS(62), 2,
      sym__dedent,
      sym_type,
  [251] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_type,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [265] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(64), 1,
      sym__newline,
    STATE(24), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [281] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(66), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [297] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_attribute_name,
    ACTIONS(68), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym_statement_repeat1,
    STATE(33), 1,
      sym_attribute,
  [313] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_type,
    ACTIONS(70), 1,
      sym__dedent,
    STATE(17), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [327] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__indent,
    STATE(31), 1,
      sym_block,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym_type,
  [341] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_type,
    STATE(14), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_type,
    STATE(25), 2,
      sym_statement,
      aux_sym_document_repeat1,
  [363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_type,
  [371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      sym_type,
  [379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_type,
  [387] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      sym__dedent,
      sym_type,
  [395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      sym__newline,
      sym_attribute_name,
  [403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      sym__dedent,
      sym_type,
  [411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym__newline,
      sym_attribute_name,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 2,
      sym__dedent,
      sym_type,
  [427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      sym__newline,
      sym_attribute_name,
  [435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      sym__dedent,
      sym_type,
  [443] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      sym__dedent,
      sym_type,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      sym__newline,
      sym_attribute_name,
  [459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      sym__newline,
      sym_attribute_name,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      sym_type,
  [475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      sym_type,
  [483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
  [490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 19,
  [SMALL_STATE(6)] = 33,
  [SMALL_STATE(7)] = 47,
  [SMALL_STATE(8)] = 63,
  [SMALL_STATE(9)] = 79,
  [SMALL_STATE(10)] = 93,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 121,
  [SMALL_STATE(13)] = 137,
  [SMALL_STATE(14)] = 153,
  [SMALL_STATE(15)] = 167,
  [SMALL_STATE(16)] = 181,
  [SMALL_STATE(17)] = 195,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 237,
  [SMALL_STATE(21)] = 251,
  [SMALL_STATE(22)] = 265,
  [SMALL_STATE(23)] = 281,
  [SMALL_STATE(24)] = 297,
  [SMALL_STATE(25)] = 313,
  [SMALL_STATE(26)] = 327,
  [SMALL_STATE(27)] = 341,
  [SMALL_STATE(28)] = 352,
  [SMALL_STATE(29)] = 363,
  [SMALL_STATE(30)] = 371,
  [SMALL_STATE(31)] = 379,
  [SMALL_STATE(32)] = 387,
  [SMALL_STATE(33)] = 395,
  [SMALL_STATE(34)] = 403,
  [SMALL_STATE(35)] = 411,
  [SMALL_STATE(36)] = 419,
  [SMALL_STATE(37)] = 427,
  [SMALL_STATE(38)] = 435,
  [SMALL_STATE(39)] = 443,
  [SMALL_STATE(40)] = 451,
  [SMALL_STATE(41)] = 459,
  [SMALL_STATE(42)] = 467,
  [SMALL_STATE(43)] = 475,
  [SMALL_STATE(44)] = 483,
  [SMALL_STATE(45)] = 490,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 3),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 5), SHIFT_REPEAT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 7),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 5, 0, 7),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 1, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_positional_value, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 6),
  [92] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_indent_external_scanner_create(void);
void tree_sitter_indent_external_scanner_destroy(void *);
bool tree_sitter_indent_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_indent_external_scanner_serialize(void *, char *);
void tree_sitter_indent_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_indent(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_indent_external_scanner_create,
      tree_sitter_indent_external_scanner_destroy,
      tree_sitter_indent_external_scanner_scan,
      tree_sitter_indent_external_scanner_serialize,
      tree_sitter_indent_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "indent",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
